# -*- coding: utf-8 -*-
"""
설정 패키지 (config)

LLM 기반 파일 분류 프로그램의 전역 설정값을 관리합니다.
"""

from .config import (
    PROJECT_ROOT,
    LOGS_DIR,
    UNDO_HISTORY_FILE,
    DEFAULT_CATEGORIES,
    LOG_LEVEL,
    LOG_FILE,
    OPENAI_API_KEY,
    LLM_MODEL,
    LLM_TEMPERATURE,
    LLM_MAX_TOKENS,
    SUPPORTED_EXTENSIONS,
    MONITOR_ENABLED,
    MONITOR_INTERVAL,
    MONITOR_DEBOUNCE_TIME,
    LOG_FORMAT,
    LOG_DATE_FORMAT,
    GUI_WINDOW_WIDTH,
    GUI_WINDOW_HEIGHT,
    MAX_FILE_SIZE,
    FILE_CONFLICT_STRATEGY,
    MAX_WORKERS,
    TIMEOUT,
    validate_config
)

__all__ = [
    'PROJECT_ROOT',
    'LOGS_DIR',
    'UNDO_HISTORY_FILE',
    'DEFAULT_CATEGORIES',
    'LOG_LEVEL',
    'LOG_FILE',
    'OPENAI_API_KEY',
    'LLM_MODEL',
    'LLM_TEMPERATURE',
    'LLM_MAX_TOKENS',
    'SUPPORTED_EXTENSIONS',
    'MONITOR_ENABLED',
    'MONITOR_INTERVAL',
    'MONITOR_DEBOUNCE_TIME',
    'LOG_FORMAT',
    'LOG_DATE_FORMAT',
    'GUI_WINDOW_WIDTH',
    'GUI_WINDOW_HEIGHT',
    'MAX_FILE_SIZE',
    'FILE_CONFLICT_STRATEGY',
    'MAX_WORKERS',
    'TIMEOUT',
    'validate_config'
]
